config/routes.rb
Rails.application.routes.draw do

devise_for :users do
  get '/logout' => 'devise/sessions#destroy'
end

  resources :movers do
    collection do
      # patch '/movers/:mover_id', to: 'movers#remove_mover'
      get 'removemover'
    end
    resources :reviews
  end

  resources :movees do
    resources :moving_events do
      collection do
        get 'complete_event'
      end
      resources :requests
      resources :giveaways
    end
  end

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'devise/sessions#destroy'
  # delete '/logout' => 'devise/sessions#destroy'

  root 'pages#home'
post '/movers/:mover_id/moving_events/new' => 'moving_events#create'
end

app/models/mover.rb
class Mover < ApplicationRecord
  belongs_to :moving_event, optional: true
  has_many :movees, through: :moving_event
  has_one :user, as: :meta, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :requests, dependent: :destroy
  accepts_nested_attributes_for :user

  geocoded_by :full_address
  after_validation :geocode, if: ->(obj){ obj.full_address.present? and obj.location_city_changed?}

  def full_name
    self.first_name + ' '+ self.last_name
  end

  def location
    self.location_street + ', ' + self.location_city + ' '+ self.location_state
  end

  def full_address
    [self.location_street, self.location_city, self.location_state ].compact.join(', ')
  end

  def karma_points_increase(increment)
    self.karma_points += increment
  end
end

app/controllers/movers_controller.rb
class MoversController < ApplicationController
  before_action :find_mover, only: [:show, :edit, :update, :destroy]
  before_action :find_moving_event, only:[:update]
  before_action :all_moving_events
  before_action :find_close_events, only:[:show]


  def new
    @mover = Mover.new
    @mover.build_user

  end

  def create
    current_user
    @mover = Mover.new(mover_params)
    p "User attributes #{mover_params}"
    # @mover.create_user(mover_params[:user_attributes])
    @mover.karma_points = 0
    if @mover.save!
      redirect_to @mover
    else
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @moving_event.movers.count <= @moving_event.movers_needed
        p @mover.moving_event_id = @moving_event.id
        @mover.movee_id = @moving_event.movee_id
        # @moving_event != nil ? @mover.movee_id = @moving_event.movee_id : @mover.movee_id = nil
        if @mover.update(mover_params)
          flash[:notice] = "Successfully updated"
          redirect_to movee_moving_event_path(@mover.movee_id, @mover.moving_event_id)
        else
          render 'edit'
        end
    else
      flash[:notice] = "Movers are not needed please try again"
    end
  end

  def show
  end

  def destroy
    @user = User.find_by(meta_id: @mover.id)
    @user.destroy
    @mover.requests.each do |request|
      request.destroy
    end
    @mover.reviews.each do |review|
      review.destroy
    end
    @mover.destroy

    redirect_to root_path

  end

  def index
    @movers = Mover.all
  end

  def removemover
    @mover = Mover.find(params[:id])
    @mover.moving_event_id = nil
    @mover.movee_id = nil
    @mover.save

    redirect_to movee_path(current_user.meta_id)
  end

  private

  def mover_params
    params.require(:mover).permit(:first_name, :last_name, :age, :occupation, :phone_number, :location_street, :location_city, :location_state, :moving_event_id, user_attributes: [ :id, :username, :email, :password ])
  end

  def find_mover
    @mover = Mover.find(params[:id])
  end

  def all_moving_events
    @moving_events = MovingEvent.all
  end

  def find_moving_event
    @moving_event = MovingEvent.find(params[:id])
  end

  def find_movee
    @movee = Movee.find(params:[:movee_id])
  end

  def find_close_events
    @close_events = []
    MovingEvent.all.each do |event|
      if @mover.distance_to(event, :mi) < 40
        @close_events<< event
      end
    end
    return @close_events
  end

  def find_user
    @user = User.find_by(meta_id)
  end


end

app/helpers/movers_helper.rb
module MoversHelper
end

app/views/movers/_forms.html.erb
<div class="forms">
  <%=form_for(@mover) do |f|%>
  <%= f.text_field :first_name, placeholder: 'First Name', class:'name_input' %>
  <%= f.text_field :last_name, placeholder: 'Last Name', class:'name_input' %><br>
  <%=f.fields_for(:user_attributes) do |u|%>
    <%= u.email_field :email, placeholder: 'What is your email?', class:'email_input'%><br>
    <%= u.text_field :username, placeholder: 'username', class:'username_input'%><br>
    <%= u.password_field :password, placeholder:'Create a password'%><br>
  <%end%>
  <%= f.number_field :age, placeholder: 'Age'%><br>
  <%= f.text_field :occupation, placeholder: 'occupation' %><br>
  <%=label_tag 'Address: Street, City, State'%><br>
  <%= f.text_field :location_street, placeholder:'Street'%>
  <%= f.text_field :location_city, placeholder:'City'%>
  <%= f.text_field :location_state, placeholder:'State'%> <br>
  <%=label_tag 'Phone Number'%><br>
  <%=f.telephone_field(:phone_number)%><br>
  <%= f.submit 'Create', class:'submit-btns'%>
  <%end%>
</div>

app/views/movers/edit.html.erb
<h1><%=@mover.full_name%></h1>
<%= render 'forms'%>

app/views/movers/index.html.erb
<h1>List of available movers</h1>
<div class="index">
  <ol>
    <%@movers.each do |m|%>
    <li><%=link_to m.full_name, m%></li>
    <%end%>
  </ol>

</div>

app/views/movers/new.html.erb
<center><h1>Movers#new</h1><center>
<center><h3>Become a Mover</h3><center>

<%= render 'forms'%>

app/views/movers/removemover.js.erb
$('.terminate').bind('ajax:success', function(){
  console.log('deleting...');
  $(this).closest('li').fadeOut();
});

app/views/movers/show.html.erb
<div class="profile_container">
<div class="profile_info">
  <div class="">
    <h1><%=@mover.full_name%></h1>
    <p><%= @mover.user.email%></p>
  </div>
  <div class="profile_pic">
    <img src="https://uwclintoncounty.org/wp-content/uploads/2017/12/united-way-headshot-empty.png" alt="">
  </div>
  <div class="">
    <p>Search location: <br><%= @mover.location%></p>
    <p>Age: <%= @mover.age%></p>
    <p>Phone Number: <%= @mover.phone_number%></p>
    <p>Karma Points:<%=@mover.karma_points%></p>
  </div>

  <% if current_user.meta_type == "Mover" && current_user.meta_id == @mover.id%>
  <%= link_to 'Edit your Account', edit_mover_path(@mover.id)%><br>
  <%=link_to "Delete Account", mover_path(@mover.id), method: :delete, data: { confirm: "Are you sure you want to delete your account #{@mover.full_name}?"}%>
  <%end%>
</div>

<div class="map">
  <%event_params = ''%>
  <%marker =('A'..'Z').to_a %>
  <%index = 0 %>
  <% if @close_events != nil%>
    <% @close_events.each do |event|%>
    <% event_params<< "&markers=color:green%7Clabel:#{marker[index]}%7C#{event.latitude},#{event.longitude}" %>
    <% index == 26? index = 0 : index += 1 %>
    <%end%>
  <%end%>
  <% if @close_events != nil %>
  <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@mover.latitude},#{@mover.longitude}&markers=#{@mover.latitude},#{@mover.longitude}#{event_params}&zoom=11&size=640x400&key=AIzaSyDs5XjtC_PfhFPV7Yl7RCO185HnKnHqlfY",
  class: 'img-fluid img-rounded', alt: "#{@mover.full_name} on the map"%>
  <%else%>
  <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@mover.latitude},#{@mover.longitude}&markers=#{@mover.latitude},#{@mover.longitude}&zoom=11&size=640x400&key=AIzaSyDs5XjtC_PfhFPV7Yl7RCO185HnKnHqlfY",
  class: 'img-fluid img-rounded', alt: "#{@mover.full_name} on the map"%>
  <%end%>

<%if @close_events != nil%>

  <div class="close_events_scroll">
    <%= form_for @mover, :url => {:controller => 'movers', :action => "update"} do %>
    <%=collection_select(:mover, :moving_event_id, @close_events, :id, :name)%><br>
    <%=submit_tag 'HELP MOVE', class:"submit"%>
    <% end%>
  </div>


<%else%>
  <h1>No one is currently moving in your Area </h1>
<%end%>

</div>

<div class="profile_search">
  <h3>Current Moving Event</h3>
  <%if !@mover.moving_event.nil?%>
  <%=link_to "#{@mover.moving_event.name}", movee_moving_event_path(@mover.moving_event.movee_id, @mover.moving_event.id)%>
  <%end%>

  <h3>Moving Events available</h3>
  <ol type="A">
    <% @close_events.each do |event|%>
    <li><%= link_to event.name, movee_moving_event_path(event.movee_id, event.id)%><br> Start Time: <%=event.start_time%><br> <%=event.location%></li>

    <br><br>
    <%end%>

  </ol>
</div>




  <ol class="ratings">
    <% if current_user.meta_type == "Movee"%>
    <%= link_to 'Leave a Review', new_mover_review_path(@mover.id), class:'leave_review'%>
    <%end%>
    <h2>Reviews and Ratings</h2>
    <%@mover.reviews. each do |review|%>
    <%if review.comment != ''%>
    <li><h3><%= review.comment%></h3>
      Rating:
      <div class="mover_stars">
        <%(review.mover_rating).times do%>
        <div class="stars">
          <img src="http://pngimg.com/uploads/star/star_PNG41531.png" alt="">
        </div>
        <%end%>
      </div>

    </li>
    <hr>
    <%end%>
    <%end%>
  </ol>



  <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
  <% end %>
</div>