config/routes.rb
Rails.application.routes.draw do

devise_for :users do
  get '/logout' => 'devise/sessions#destroy'
end

  resources :movers do
    collection do
      # patch '/movers/:mover_id', to: 'movers#remove_mover'
      get 'removemover'
    end
    resources :reviews
  end

  resources :movees do
    resources :moving_events do
      collection do
        get 'complete_event'
      end
      resources :requests
      resources :giveaways
    end
  end

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'devise/sessions#destroy'
  # delete '/logout' => 'devise/sessions#destroy'

  root 'pages#home'
post '/movers/:mover_id/moving_events/new' => 'moving_events#create'
end

app/models/moving_event.rb
class MovingEvent < ApplicationRecord
  has_many :movers, dependent: :nullify
  has_one :movee
  has_many :requests, dependent: :destroy
  has_many :giveaways, dependent: :destroy
  geocoded_by :full_address
  after_validation :geocode, if: ->(obj){ obj.full_address.present?}

  def full_address
    [self.old_location_street, self.old_location_city, self.old_location_state ].compact.join(', ')
  end

  def new_full_address
    [self.new_location_street, self.new_location_city, self.new_location_state ].compact.join(', ')
  end

  def location
    self.old_location_street + ' ' + self.old_location_city + ' '+ self.old_location_state
  end

  def new_location
    self.new_location_street + ' ' + self.new_location_city + ' '+ self.new_location_state
  end

  def event_time
    self.start_time.hour + ':' + self.start_time.min
  end

  def format_time
    new_time = self.start_time.split(":")
      if new_time[0].to_i > 12
          new_time[0] = (new_time[0].to_i - 12).to_s
      else
      new_time[0] = new_time[0].split('').pop
      return new_time.join(":") + " "+ "am"
      end
      return new_time.join(":") + " "+ "pm"
  end
end

app/controllers/moving_events_controller.rb
class MovingEventsController < ApplicationController
  before_action :find_moving_event, except:[:new, :create, :index]
  before_action :find_movee


  def new
    @moving_event = MovingEvent.new
    flash[:notice] = 'Please Sign up to create a moving event '
  end

  def create
    @moving_event = MovingEvent.new(moving_event_params)
    @moving_event.movee_id = @movee.id
    if @moving_event.save
      redirect_to movee_moving_events_path(@movee.id, @moving_event.id)
    else
      render 'new'
    end
  end

  def index
    @moving_event = MovingEvent.all
  end

  def edit
  end

  def update
    if @moving_event.update(moving_event_params)
      flash[:notice] = "Successfully updated"
      redirect_to movee_moving_event_path(@movee.id, @moving_event.id)
    else
      render 'edit'
    end
  end

  def destroy
    @moving_event.requests.each do |request|
      request.destroy
    end
    @moving_event.movers.each do |mover|
      mover.moving_event_id = nil
    end

    @moving_event.giveaways.each do |giveaway|
      giveaway.destroy
    end
    @moving_event.destroy
    redirect_to movee_path(@movee.id)

  end

  def show
  end

  def complete_event
    @moving_event = MovingEvent.find(params[:moving_event_id])
    @moving_event.movers.each do |mover|
        if mover.karma_points != nil
            if @moving_event.difficulty == 'easy'
              mover.karma_points_increase(3)
            elsif @moving_event.difficulty == 'medium'
              mover.karma_points_increase(6)
            else
              mover.karma_points_increase(9)
            end
        end
        mover.save
    end
    redirect_to movee_moving_event_path(@movee.id, @moving_event.id)

  end

  private

  def moving_event_params
    params.require(:moving_event).permit(:name, :start_date, :start_time,:description, :old_location_street, :old_location_city, :old_location_state, :new_location_street, :new_location_city, :new_location_state, :amount_of_furniture, :difficulty, :movers_needed, :estimate_hours, :payment_per_hour, :mover_id, :movee_id)
  end

  def find_movee
    @movee = Movee.find(params[:movee_id])
    p params[:id]
  end

  def find_moving_event
    @moving_event = MovingEvent.find(params[:id])
  end

  def find_mover
    @movers = Mover.find(params[:mover_id])
  end

end

app/helpers/moving_events_helper.rb
module MovingEventsHelper
end

app/views/moving_events/_forms.html.erb
<div class="event_forms">
  <%= form_for([@movee, @moving_event]) do |f|%>
  <%=label_tag 'Event Name'%><br>
  <%= f.text_field :name, placeholder:'Name of your Event', class:'name_input'%><br><br>
  <%= label_tag 'Event description'%><br>
  <%= f.text_area :description, placeholder: 'Details of the event'%><br>
  <%= label_tag 'Old Address: Street, City, State'%><br>
  <%= f.text_field :old_location_street, placeholder:'Street' %>
  <%= f.text_field :old_location_city, placeholder:'City' %>
  <%= f.text_field :old_location_state, placeholder:'State' %><br>
  <%= label_tag 'New Address: Street, City, State'%><br>
  <%= f.text_field :new_location_street, placeholder:'Street' %>
  <%= f.text_field :new_location_city, placeholder:'City' %>
  <%= f.text_field :new_location_state, placeholder:'State' %><br>
  <%= label_tag 'Start Date'%><br>
  <%= f.date_field :start_date, placeholder: 'Start Date'%><br>
  <%= label_tag 'Start Time'%><br>
  <%= f.time_field :start_time, :value => "%l:%M%P", :ampm => true %><br>
  <%= f.number_field :estimate_hours, placeholder: "Estimated Time Needed"%> Hours <br>
  <%= label_tag 'Degree of difficulty'%><br>
  <%= f.select :difficulty, ['easy','medium', 'hard' ], class: 'dropdown'%><br>
  <%= f.number_field :amount_of_furniture, placeholder: 'Amount of furniture'%><br>
  <%= f.number_field :movers_needed, placeholder: 'Amount of movers needed'%><br>
  <%= label_tag 'Payment per hour'%><br>
  <%= f.number_field :payment_per_hour, placeholder:"Payment per hour"%><br>

  <%= f.submit "Create" %>

  <%end%>

</div>

app/views/moving_events/edit.html.erb
<center><h1><%= @moving_event.name%></h1><center>
<center><h2>Edit Information</h2><center>
<%= render 'forms'%>

app/views/moving_events/index.html.erb
<h1>Moving Events Planned</h1>
<div class="list_index">
    <% @movee.moving_events.each do |e|%>

    <li><%=link_to e.name, movee_moving_event_path(@movee.id, e.id), class:"list"%></li>

    <%end%>
</div>

app/views/moving_events/new.html.erb
<% if current_user.meta_type == 'Movee'%>
<h1>Describe your move</h1>
<%= render 'forms'%>
<% else%>
<%=flash[:notice]%>
<%end%>

app/views/moving_events/show.html.erb
<div class="profile_container">
  <div class="event_info">
    <ul id = "event_description">
      <h1><%=@moving_event.name%></h1>
      <% if current_user.meta_type == "Mover" && current_user.meta.moving_event_id == @moving_event.id%>
      <li>Planner: <%=link_to @movee.full_name, movee_path(@movee.id)%></li>
      <%else%>
      <li>Planner: &nbsp <%= @movee.full_name%></li>
      <%end%>
      <li>Starting Day: &nbsp <%=@moving_event.start_date.strftime("%m/%d/%y")%></li>
      <li>Start Time: &nbsp <%=@moving_event.format_time%></li>
      <li>From: <br><%=@moving_event.location%></li>
      <% if current_user.meta_type == 'Movee' && current_user.meta_id == @moving_event.movee_id%>
      <li>To: <br><%=@moving_event.new_location%></li>
      <%elsif current_user.meta_type == 'Mover' && current_user.meta.moving_event_id == @moving_event.id%>
      <li>To: <br><%=@moving_event.new_location%></li>
      <%end%>
      <li><%=@moving_event.payment_per_hour%> dollars per hour</li>
    </ul>
    <div class="event_choices">
      <% if current_user.meta_type == "Mover"%>
      <%= link_to "Make a request",{:controller => "requests", :action => "create", :moving_event_id => @moving_event.id, :mover_id => current_user.meta_id, :status => 'Pending'}, :method => :post %><br>
      <%end%>
      <% if current_user.meta_type == 'Movee' && current_user.meta_id == @moving_event.movee_id%>
      <%= link_to 'Edit', edit_movee_moving_event_path(@movee.id, @moving_event.id)%><br>
      <%= link_to "Remove Moving Event", movee_moving_event_path(@movee.id, @moving_event.id), method: :delete, data: { confirm: "Are you sure you want to delete #{@moving_event.name} ?"}%><br>
      <%= link_to "Reward points to movers", controller:'moving_events', action:'complete_event', :id => @moving_event.id, :moving_event_id => @moving_event.id, :method => :get %><br>
      <%= link_to "Add Give aways", new_movee_moving_event_giveaway_path(@movee.id, @moving_event.id)%>
      <%end%>

    </div>
  </div>
  <div class="map">
    <% if current_user.meta_type == "Movee" && current_user.meta_id == @moving_event.movee_id %>
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@moving_event.latitude},#{@moving_event.longitude}&markers=color:green%7Clabel:A%7C#{@moving_event.latitude},#{@moving_event.longitude}&markers=color:blue%7Clabel:B%7C#{@moving_event.new_full_address}&zoom=10&size=640x400&key=AIzaSyDs5XjtC_PfhFPV7Yl7RCO185HnKnHqlfY",
    class: 'img-fluid img-rounded', alt: "#{@moving_event.name} on the map"%>
    <%elsif current_user.meta_type == "Mover" && current_user.meta.moving_event_id == @moving_event.id %>
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@moving_event.latitude},#{@moving_event.longitude}&markers=color:green%7Clabel:A%7C#{@moving_event.latitude},#{@moving_event.longitude}&markers=color:blue%7Clabel:B%7C#{@moving_event.new_full_address}&zoom=10&size=640x400&key=AIzaSyDs5XjtC_PfhFPV7Yl7RCO185HnKnHqlfY",
    class: 'img-fluid img-rounded', alt: "#{@moving_event.name} on the map"%>
    <% else %>
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@moving_event.latitude},#{@moving_event.longitude}&markers=color:green%7Clabel:A%7C#{@moving_event.latitude},#{@moving_event.longitude}&zoom=10&size=640x400&key=AIzaSyDs5XjtC_PfhFPV7Yl7RCO185HnKnHqlfY",
    class: 'img-fluid img-rounded', alt: "#{@moving_event.name} on the map"%>
    <%end%>
  </div>
  <div class="ratings">
    <ol>
      <h2>The Crew</h2>
      <% @moving_event.movers.each do |mover|%>
      <li><%= link_to mover.full_name, mover%>
        <% if current_user.meta_type == 'Movee' && current_user.meta_id == @moving_event.movee_id%>
        <%=link_to 'remove', controller:'movers', action:'removemover' , :id => mover.id, :moving_event_id => nil, :movee_id => nil, :method => :get, class:"mover_remove" %></li>
        <%end%>
        <%end%>
      </ol>
  </div>

  <div class="ratings">
    <h2>Incentives</h2>

    <ol>
      <% @moving_event.giveaways.each do |giveaway|%>
        <li><%=giveaway.item_name%> -
          Condition: <%=giveaway.condition%><br>
          <% if current_user.meta_type == "Movee" && current_user.meta_id == giveaway.moving_event.movee_id%>
          <i><%= link_to 'Remove Item', movee_moving_event_giveaway_path(@movee.id, @moving_event.id, giveaway.id),  method: :delete, data: { confirm: "Are you sure you want to delete #{giveaway.item_name} ?", remote:true}, class:'fas fa-trash terminate'%></i>
          <%end%>
         </li>
      <%end%>
    </ol>

  </div>



</div>