config/routes.rb
Rails.application.routes.draw do

devise_for :users do
  get '/logout' => 'devise/sessions#destroy'
end

  resources :movers do
    collection do
      # patch '/movers/:mover_id', to: 'movers#remove_mover'
      get 'removemover'
    end
    resources :reviews
  end

  resources :movees do
    resources :moving_events do
      collection do
        get 'complete_event'
      end
      resources :requests
      resources :giveaways
    end
  end

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'devise/sessions#destroy'
  # delete '/logout' => 'devise/sessions#destroy'

  root 'pages#home'
post '/movers/:mover_id/moving_events/new' => 'moving_events#create'
end

app/models/movee.rb
class Movee < ApplicationRecord

  has_many :moving_events
  has_many :movers, through: :moving_events
  has_one :user, as: :meta, dependent: :destroy
  has_many :giveaways, through: :moving_events
  accepts_nested_attributes_for :user

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def location
    self.location_street + ', ' + self.location_city + ' '+ self.location_state
  end
end

app/controllers/movees_controller.rb
class MoveesController < ApplicationController
  before_action :find_movee, only: [:show, :edit, :update, :destroy]

  def new
    @movee = Movee.new
    @movee.build_user
  end

  def create
    @movee = Movee.new(movee_params)
      p "User attributes #{movee_params}"
    if @movee.save
      redirect_to @movee
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    
  end

  def show

  end

  def index
    @movees = Movee.all
  end

  def destroy
  end


  private

  def movee_params
    params.require(:movee).permit(:first_name, :last_name, :age, :email, :occupation, :location_street, :location_city, :location_state, :phone_number, user_attributes: [ :id, :username, :email, :password ])
  end

  def find_movee
    @movee = Movee.find(params[:id])
  end
end

app/helpers/movees_helper.rb
module MoveesHelper
end

app/views/movees/_forms.html.erb
<div class="forms">
  <%=form_for(@movee) do |f|%><br>
  <%= f.text_field :first_name, placeholder: 'First Name' ,require: true %>
  <%= f.text_field :last_name, placeholder: 'Last Name' ,require: true %><br>
  <%=f.fields_for(:user_attributes) do |u|%>
    <%= u.email_field :email, placeholder: 'What is your email?',require: true %><br>
    <%= u.text_field :username, placeholder: 'username', require: true %><br>
    <%= u.password_field :password, placeholder:'Create a password', require: true %><br>
  <%end%>
  <%= f.number_field :age, placeholder: 'Age', require:true %><br>
  <%=label_tag 'location: Street, City, State'%><br>
  <%= f.text_field :location_street, placeholder: 'Street', require: true%>
  <%= f.text_field :location_city, placeholder: 'City', require: true %>
  <%= f.text_field :location_state, placeholder: 'State' %> <br>
  <%=label_tag 'Phone Number'%><br>
  <%=f.telephone_field(:phone_number, placeholder:'Phone Number') %><br>
  <%= f.submit 'Create', class:'submit-btns'%>
  <%end%>

</div>

app/views/movees/edit.html.erb
<h1><%=@movee.full_name%></h1>

<%=render 'forms'%>

app/views/movees/index.html.erb
<h1>Movees#index</h1>
<p>Find me in app/views/movees/index.html.erb</p>

app/views/movees/new.html.erb
<center><h1>Find Movers</h1><center>
<center><h4>Need help moving? Sign up to get help from available movers</h4><center>
<%= render 'forms'%>

app/views/movees/show.html.erb
<% if (current_user.meta_type == 'Movee' && current_user.meta_id == @movee.id)||( current_user.meta_type == 'Mover' && current_user.meta.movee_id == @movee.id) %>
<div class="movee_profile">
  <div class="profile_info">
      <div class="">
        <h1><%=@movee.full_name%></h1>
        <h4><%=@movee.user.email%></h4>
      </div>
      <div class="profile_pic">
        <img src="https://uwclintoncounty.org/wp-content/uploads/2017/12/united-way-headshot-empty.png" alt="">
      </div>
      <div class="">
      <% if current_user.meta_type == "Movee" && current_user.meta_id == @movee.id%>
        <p><%=link_to 'Look up Movers', movers_path%></p>
        <p><%=link_to 'Create a moving event', new_movee_moving_event_path(@movee.id)%></p>
        <%= link_to 'Edit your Account', edit_movee_path(@movee.id)%><br>
        <p><%=link_to 'Delete Account', movee_path(@movee.id), method: :delete, data: { confirm: "Are you sure you want to delete your account, #{@movee.full_name}?"}%></p>
      <% end %>
      </div>
  </div>
  <div class="ratings" id="list_movers">
    <h2 class="underline">List of Movers</h2>
    <%@movee.movers.each do |mover|%>
      <li><%=mover.full_name%></li>
    <%end%>
  </div>
  <div class="profile_search">
    <center><h2>Recent Events</h2><center>
    <ol>
      <% @movee.moving_events.each do |event|%>
        <li><%=link_to event.name, movee_moving_event_path(@movee.id, event.id), class:'moving_event_name'%>
          <i><%=link_to 'Destroy', movee_moving_event_path(@movee.id, event.id), method: :delete, data: { confirm: 'Are you sure you want to delete this event?'}, class:'far fa-calendar-edit'%></i>
        </li>
        <p>Movers needed:
          <%=event.movers_needed%></p>
        <p>Movers available:
          <%=event.movers.count%></p>
        <%event.requests.each do |request|%>
          Request #<%=request.id%>:<%=request.status%>
          <br>
          <%= link_to 'Accept', movee_moving_event_request_path(@movee.id, event.id, request.id), :id => current_user.meta_id, :moving_event_id => request.moving_event.id, :mover_id => request.mover.id, :status => 'Accepted', method: :put %>
          OR
          <%= link_to 'Reject'%>
        <%end%>
      <%end%>
    </ol>

  </div>

  <div class="ratings">
    <h2>Items being given away</h2>
    <ol>
      <%@movee.giveaways.each do |giveaway|%>
      <li><%= giveaway.item_name%></li>
      <%end%>
    </ol>

  </div>

</div>

<%else%>
<h2 class="flash"><%=flash[:notice] = "You are not authorized to see this page. Please try again"%></h2>
<%end%>